**Numpy Tutorials**

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

**What is an array**

An array is a data structure that stores values of same data type. 
In Python, this is the main difference between arrays and lists. 
In python, lists can contain values corresponding to different data types, but arrays can only contain values corresponding to same data type.

In [37]:
import numpy as np

In [38]:
my_lst = [1, 2, 3, 4, 5]
arr = np.array(my_lst)

In [39]:
print(arr)

[1 2 3 4 5]


In [40]:
type(arr)

numpy.ndarray

In [41]:
arr

array([1, 2, 3, 4, 5])

In [42]:
arr.shape

(5,)

**Multi Dimention Array**

In [43]:
list1 = [1, 2, 3, 4, 5]
list2 = [11, 12, 13, 14, 15]
list3 = [21, 22, 23, 24, 25]

In [44]:
arr1 = np.array([list1, list2, list3])

In [45]:
arr1

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [46]:
arr1.shape

(3, 5)

In [47]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5, 11],
       [12, 13, 14],
       [15, 21, 22],
       [23, 24, 25]])

**Indexing**

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[2]

3

In [50]:
arr[1:4]


array([2, 3, 4])

In [51]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr1

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [53]:
arr1[1:,3:]

array([[14, 15],
       [24, 25]])

In [54]:
arr1[0:,2:]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25]])

In [55]:
arr1[:,:]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [56]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [57]:
arr3 = arr.copy()
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr3[3:] = 100
arr3

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr < 2

array([ True, False, False, False, False, False, False, False, False])

In [61]:
arr * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [73]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.ones(4)

array([1., 1., 1., 1.])

In [75]:
np.ones((2, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [77]:
np.ones((3, 4), dtype = bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [81]:
## Random distribution
np.random.rand(3,3)

array([[0.53867983, 0.33321069, 0.40656636],
       [0.72116197, 0.23474197, 0.74554585],
       [0.80591447, 0.26103694, 0.02401452]])